---
type: workflow
version: 1
name: build
inputs:
  parameters:
    commit:
      default: "%%session.commit%%"
    repo:
      default: "%%session.repo%%"
    docs-branch:
      default: "master"
    href-base:
      default: "/"
    base-url:
      default: ""
    tracking-id:
      default: ""
steps:
- checkout-site:
    template: argo-checkout
  checkout-docs:
    template: argo-checkout
    arguments:
      parameters.repo: https://github.com/argoproj/docs.git
      parameters.commit: "%%inputs.parameters.docs-branch%%"
- build-site:
    image: node:6.3.1
    command: ["bash", "-c"]
    env:
      - name: HREF_BASE
        value: "%%inputs.parameters.href-base%%"
      - name: TRACKING_ID
        value: "%%inputs.parameters.tracking-id%%"
      - name: BASE_URL
        value: "%%inputs.parameters.base-url%%"
    args: ["cd /src && npm install && npm run build:prod"]
    resources:
      mem_mib: 1536
      cpu_cores: 0.2
    inputs:
      artifacts:
        code:
          from: "%%steps.checkout-site.outputs.artifacts.code%%"
          path: /src
    outputs:
      artifacts:
        code:
          path: /src
- prepare:
    image: node:6.3.1
    command: ["bash", "-c"]
    args: ["cd /argo-site && ./scripts/copy-docs.sh && npm run prerender:prod"]
    env:
      - name: HREF_BASE
        value: "%%inputs.parameters.href-base%%"
      - name: TRACKING_ID
        value: "%%inputs.parameters.tracking-id%%"
      - name: BASE_URL
        value: "%%inputs.parameters.base-url%%"
    resources:
      mem_mib: 1536
      cpu_cores: 0.2
    inputs:
      artifacts:
        docs-code:
          from: "%%steps.checkout-docs.outputs.artifacts.code%%"
          path: /argo-docs
        site-code:
          from: "%%steps.build-site.outputs.artifacts.code%%"
          path: /argo-site
    outputs:
      artifacts:
        code:
          path: /argo-site
outputs:
  artifacts:
    code:
      from: "%%steps.prepare.outputs.artifacts.code%%"
